version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord-py
    versions:
    - 1.7.0
  - dependency-name: python-dotenv
    versions:
    - 0.16.0
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
