name: Aqua
on:
  # Trigger workflow for push and pull requests
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test"